### ISSUE TITLE
Replication slot does not exist issue

### ISSUE THREAD

**Issue by hookenful** [toluaina/pgsync#302]
PGSync version: 2.2.1

Postgres version: 14.2

Elasticsearch version:  7.11.2

Redis version: 6.2-alpine

Python version: 3.7-slim

Problem Description: 

Getting this strange error while starting

Error Message (if any): 

```
:RuntimeError: Replication slot "profile_departments" does not exist.
![image](https://user-images.githubusercontent.com/31849464/176518421-17c22d86-65b9-42b1-b63e-9a96d2b204e4.png)

```

Mine `Dockerfile`

```
FROM python:3.7-slim

WORKDIR /usr/src/app

COPY ./ ./

RUN chmod +x ./entrypoint.sh

RUN pip install pgsync==2.2.1

RUN apt update \
    && apt install -y moreutils \
    && apt install -y jq \
    && apt install -y wait-for-it

ENTRYPOINT ["bash", "./entrypoint.sh"]
```

docker-compose:

```
pgsync:
    build: ./src/pgsync
    command: ./runserver.sh
    sysctls:
      - net.ipv4.tcp_keepalive_time=200
      - net.ipv4.tcp_keepalive_intvl=200
      - net.ipv4.tcp_keepalive_probes=5
    labels:
      org.label-schema.name: "pgsync"
      org.label-schema.description: "Postgres to elasticsearch sync"
      com.label-schema.service-type: "daemon"
    networks:
      - coffeeface
    depends_on:
      - coffeefacedb
      - redis
      - elasticsearch
    environment:
      - PG_USER=postgres
      - PG_HOST=coffeefacedb
      - PG_PASSWORD=postgres
      - LOG_LEVEL=INFO
      - ELASTICSEARCH_PORT=9200
      - ELASTICSEARCH_SCHEME=http
      - ELASTICSEARCH_HOST=elasticsearch
      - REDIS_HOST=redis
      - REDIS_AUTH=****
```

`entrypoint.sh`

```
#!/usr/bin/env bash
wait-for-it $PG_HOST:5432 -t 60
wait-for-it $REDIS_HOST:6379 -t 60
wait-for-it $ELASTICSEARCH_HOST:9200 -t 60

jq '.[].database = env.PG_DATABASE' schema.json | sponge schema.json

bootstrap --config ./schema.json
pgsync --config ./schema.json -d
```

```
  coffeefacedb:
    restart: unless-stopped
    volumes:
      - ./src/postgres/my-postgres.conf:/usr/local/etc/postgres/postgres.conf
      - coffeefacedb:/var/lib/postgresql/data
      - ./src/postgres/pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
    command: "postgres -c config_file=/usr/local/etc/postgres/postgres.conf"
    ports:
      - 5445:5432
   ```
